BEGIN TRY
    BEGIN TRANSACTION miTransaccion;

    DECLARE @PedidoId INT;

    INSERT INTO PEDIDOS (CLIENTE_ID, MONTO_TOTAL, FECHA)
    VALUES (1, 0, GETDATE());

    SET @PedidoId = SCOPE_IDENTITY();

    -- Forzar error: pedir más cantidad de la disponible
    INSERT INTO PRODUCTO_PEDIDO (PEDIDO_ID, PRODUCTO_ID, PRECIO_UNITARIO, CANTIDAD, FECHA_REGISTRO)
    SELECT @PedidoId, PRODUCTO_ID, PRECIO_UNITARIO, 9999, GETDATE()
    FROM PRODUCTOS WHERE PRODUCTO_ID = 1;

    -- Validación
    IF EXISTS (
        SELECT 1 FROM PRODUCTOS WHERE PRODUCTO_ID = 1 AND CANTIDAD < 9999
    )
        THROW 50003, 'Stock insuficiente (simulado)', 1;

    COMMIT TRANSACTION miTransaccion;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION miTransaccion;
    PRINT 'Se ejecutó ROLLBACK por: ' + ERROR_MESSAGE();
END CATCH;

-- El pedido NO debe existir
SELECT TOP 5 * FROM PEDIDOS ORDER BY PEDIDO_ID DESC;

-- El inventario NO debe haber cambiado
SELECT PRODUCTO_ID, CANTIDAD FROM PRODUCTOS WHERE PRODUCTO_ID = 1;