USE ADMINISTRACION_BASE_DATOS
GO

BEGIN TRY
    BEGIN TRANSACTION;

    DECLARE @ClienteId INT = 1;

    -- 1. Validar cliente activo
    IF NOT EXISTS (SELECT 1 FROM CLIENTES WHERE CLIENTE_ID = @ClienteId AND ESTADO = 1)
        THROW 50001, 'Cliente inválido o inactivo', 1;

    -- 2. Crear pedido
    INSERT INTO PEDIDOS (CLIENTE_ID, MONTO_TOTAL, FECHA)
    VALUES (@ClienteId, 0, GETDATE());

    DECLARE @PedidoId INT = SCOPE_IDENTITY();

    -- 3. Agregar detalle (ejemplo: 2 productos)
    -- Producto 2 (Mouse), cantidad 2
    INSERT INTO PRODUCTO_PEDIDO (PEDIDO_ID, PRODUCTO_ID, PRECIO_UNITARIO, CANTIDAD, FECHA_REGISTRO)
    SELECT @PedidoId, P.PRODUCTO_ID, P.PRECIO_UNITARIO, 2, GETDATE()
    FROM PRODUCTOS P WHERE P.PRODUCTO_ID = 2;

    -- Producto 3 (Teclado), cantidad 1
    INSERT INTO PRODUCTO_PEDIDO (PEDIDO_ID, PRODUCTO_ID, PRECIO_UNITARIO, CANTIDAD, FECHA_REGISTRO)
    SELECT @PedidoId, P.PRODUCTO_ID, P.PRECIO_UNITARIO, 1, GETDATE()
    FROM PRODUCTOS P WHERE P.PRODUCTO_ID = 3;

    -- 4. Validar y descontar inventario
    IF EXISTS (
        SELECT 1
        FROM PRODUCTO_PEDIDO D
        JOIN PRODUCTOS P ON P.PRODUCTO_ID = D.PRODUCTO_ID
        WHERE D.PEDIDO_ID = @PedidoId
          AND D.CANTIDAD > P.CANTIDAD
    )
        THROW 50002, 'Inventario insuficiente', 1;

    UPDATE P
    SET P.CANTIDAD = P.CANTIDAD - D.CANTIDAD,
        P.FECHA_MODIFICACION = GETDATE()
    FROM PRODUCTOS P
    JOIN PRODUCTO_PEDIDO D ON D.PRODUCTO_ID = P.PRODUCTO_ID
    WHERE D.PEDIDO_ID = @PedidoId;

    -- 5. Calcular total
    UPDATE PEDIDOS
    SET MONTO_TOTAL = (
        SELECT SUM(PRECIO_UNITARIO * CANTIDAD)
        FROM PRODUCTO_PEDIDO
        WHERE PEDIDO_ID = @PedidoId
    )
    WHERE PEDIDO_ID = @PedidoId;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    PRINT 'Error: ' + ERROR_MESSAGE();
END CATCH;