SELECT * 
FROM PEDIDOS 
WHERE CLIENTE_ID = 1;

--indice segun id cliente
CREATE NONCLUSTERED INDEX IX_PEDIDOS_CLIENTE
ON PEDIDOS (CLIENTE_ID);

SELECT * 
FROM PRODUCTOS 
WHERE ESTADO = 1;

--indice segun estado del producto
CREATE NONCLUSTERED INDEX IX_PRODUCTOS_ESTADO
ON PRODUCTOS (ESTADO);

SELECT * 
FROM PEDIDOS 
WHERE FECHA >= '2025-01-01';

--indice segun la fecha del pedido
CREATE NONCLUSTERED INDEX IX_PEDIDOS_FECHA
ON PEDIDOS (FECHA);


SELECT * 
FROM PEDIDOS
WHERE CLIENTE_ID = 1 
AND FECHA >= '2025-01-01';

--indice compuesto segun el cliente y la fecha del pedido
CREATE NONCLUSTERED INDEX IX_PEDIDOS_CLIENTE_FECHA
ON PEDIDOS (CLIENTE_ID, FECHA);


SELECT * 
FROM CLIENTES 
WHERE CLIENTE_ID = 1;

SELECT * 
FROM CLIENTES 
WHERE NOMBRE = 'Ana Lopez';