USE ADMINISTRACION_BASE_DATOS;

--1
SELECT C.NOMBRE, P.PEDIDO_ID, P.MONTO_TOTAL FROM CLIENTES C
INNER JOIN PEDIDOS P on C.CLIENTE_ID = P.CLIENTE_ID
---2
SELECT C.NOMBRE, P.PEDIDO_ID FROM CLIENTES C
LEFT JOIN PEDIDOS P ON C.CLIENTE_ID = P.CLIENTE_ID
---3
SELECT C.NOMBRE, P.PEDIDO_ID FROM CLIENTES C 
RIGHT JOIN PEDIDOS P ON C.CLIENTE_ID = P.CLIENTE_ID
---4
SELECT C.NOMBRE, PR.NOMBRE, PP.CANTIDAD, PP.PRECIO_UNITARIO FROM CLIENTES C
INNER JOIN PEDIDOS P ON C.CLIENTE_ID = P.CLIENTE_ID
INNER JOIN PRODUCTO_PEDIDO PP ON P.PEDIDO_ID = PP.PEDIDO_ID
INNER JOIN PRODUCTOS PR ON PP.PRODUCTO_ID = PR.PRODUCTO_ID
---5
--subquery
SELECT 
C.NOMBRE,
(
    SELECT SUM(PP.CANTIDAD * PP.PRECIO_UNITARIO)
    FROM PEDIDOS P
    INNER JOIN PRODUCTO_PEDIDO PP
        ON P.PEDIDO_ID = PP.PEDIDO_ID
    WHERE P.CLIENTE_ID = C.CLIENTE_ID
) AS TOTAL_GASTADO
FROM CLIENTES C;

-- cte
WITH TOTAL_CLIENTE AS
(
    SELECT 
        P.CLIENTE_ID,
        SUM(PP.CANTIDAD * PP.PRECIO_UNITARIO) AS TOTAL
    FROM PEDIDOS P
    INNER JOIN PRODUCTO_PEDIDO PP
        ON P.PEDIDO_ID = PP.PEDIDO_ID
    GROUP BY P.CLIENTE_ID
)

SELECT 
C.NOMBRE,
T.TOTAL
FROM TOTAL_CLIENTE T
INNER JOIN CLIENTES C
    ON T.CLIENTE_ID = C.CLIENTE_ID;


