
CREATE DATABASE ADMINISTRACION_BASE_DATOS;
GO

USE ADMINISTRACION_BASE_DATOS;
GO
CREATE TABLE CLIENTES (
    CLIENTE_ID INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(100) NOT NULL,
    CIUDAD VARCHAR(100) NOT NULL,
	ESTADO BIT NOT NULL
);
GO
CREATE TABLE PEDIDOS (
    PEDIDO_ID INT PRIMARY KEY IDENTITY(1,1),
    CLIENTE_ID INT NOT NULL,
	MONTO_TOTAL DECIMAL(10,2) NOT NULL,
    FECHA DATETIME NOT NULL,
    FOREIGN KEY (CLIENTE_ID) REFERENCES Clientes(CLIENTE_ID)
);
GO
CREATE TABLE PRODUCTOS (
	PRODUCTO_ID INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(100) NOT NULL,
	CANTIDAD INT NOT NULL,
	PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
	FECHA_REGISTRO DATETIME NOT NULL,
	FECHA_MODIFICACION DATETIME,
	ESTADO BIT NOT NULL
);
GO
CREATE TABLE PRODUCTO_PEDIDO (
    DETALLE_ID INT PRIMARY KEY IDENTITY(1,1),
    PEDIDO_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    CANTIDAD INT NOT NULL,
	FECHA_REGISTRO DATETIME NOT NULL,
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDOS(PEDIDO_ID),
	FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(PRODUCTO_ID)
);
GO

INSERT INTO CLIENTES (NOMBRE, CIUDAD, ESTADO)
VALUES
('Ana Lopez','San Ramon',1),
('Luis Mora','Alajuela',1),
('Carlos Perez','Heredia',1),
('Maria Fernandez','San Jose',1),
('Jorge Vargas','Cartago',1),
('Laura Solis','San Ramon',1),
('Pedro Ramirez','Puntarenas',1),
('Andrea Campos','Alajuela',1);
GO
INSERT INTO PRODUCTOS (NOMBRE,CANTIDAD,PRECIO_UNITARIO,FECHA_REGISTRO,FECHA_MODIFICACION,ESTADO)
VALUES
('Laptop Lenovo',15,950.00,GETDATE(),NULL,1),
('Mouse Logitech',50,25.00,GETDATE(),NULL,1),
('Teclado Mecánico',30,75.00,GETDATE(),NULL,1),
('Monitor Samsung 24',20,220.00,GETDATE(),NULL,1),
('Audifonos Sony',25,120.00,GETDATE(),NULL,1),
('Webcam HD',40,65.00,GETDATE(),NULL,1),
('Disco SSD 1TB',18,150.00,GETDATE(),NULL,1),
('Memoria RAM 16GB',35,95.00,GETDATE(),NULL,1);
GO
INSERT INTO PEDIDOS (CLIENTE_ID,MONTO_TOTAL,FECHA)
VALUES
(1,1000.00,GETDATE()),
(2,75.00,GETDATE()),
(3,220.00,GETDATE()),
(1,245.00,GETDATE()),
(4,120.00,GETDATE()),
(5,150.00,GETDATE()),
(6,65.00,GETDATE()),
(7,320.00,GETDATE());
GO
INSERT INTO PRODUCTO_PEDIDO (PEDIDO_ID,PRODUCTO_ID,PRECIO_UNITARIO,CANTIDAD,FECHA_REGISTRO)
VALUES
(1,1,950.00,1,GETDATE()),
(1,2,25.00,2,GETDATE()),

(2,3,75.00,1,GETDATE()),

(3,4,220.00,1,GETDATE()),

(4,2,25.00,1,GETDATE()),
(4,5,120.00,1,GETDATE()),
(4,6,65.00,1,GETDATE()),

(5,5,120.00,1,GETDATE()),

(6,7,150.00,1,GETDATE()),

(7,6,65.00,1,GETDATE()),

(8,4,220.00,1,GETDATE()),
(8,2,25.00,2,GETDATE()),
(8,8,95.00,1,GETDATE());